### ISSUE TITLE
Home Button functionality 

### ISSUE THREAD

**Issue by JavierRefuerzo** [UniversalDevicesInc/UD-Mobile-iOS#12]
Home Button does not take user to the beginning home screen

**Comment by BitArtOnLine** [comment]
Maybe re-think destination to take you back to the current main folder I.e. Devices and Scenes, rather than to actual home. So if in Programs in some sub-folder, Home returns to top of Programs; When in Devices, back to Device main folder, etc.

I spend most of the time in Devices..., so Home button still requires re-entering Devices again.

The better way to implement would be have 1st home click take you to top of current main folder, and from there home button would take you to top of folders tree ( real home).

**Comment by JavierRefuerzo** [comment]
I understand your point, but we have a decent amount of customers with multiple ISYs.  So, going to App Home should show all available ISYs.

I think, once favorites have been implemented, most users will only use the home tab for devices that are not used often.

**Comment by JavierRefuerzo** [comment]
Fixed in  38d3aab..77200f3
